# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - CSC490Server

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://490project.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aa9b7ee8108d43a490b83f1f4ed16bf7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6e541ecc8f9145c584b759e4fbd70db7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: 490project.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa9b7ee8108d43a490b83f1f4ed16bf7 }}/ProjectContainers/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CSC490Server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4cffc4c63c3c4d989ef85d62f74c487e }}
        images: '490project.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aa9b7ee8108d43a490b83f1f4ed16bf7 }}/ProjectContainers/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'