# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - CSC490Server

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://projectcontainers.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bbeb2f64b0a24c738e9c1b44fef7ac9f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c5ee1901a58a4705ac9df1c3fb9d2e3c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: projectcontainers.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bbeb2f64b0a24c738e9c1b44fef7ac9f }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CSC490Server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a8db5e9593954d15ac139b64e6c83160 }}
        images: 'projectcontainers.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bbeb2f64b0a24c738e9c1b44fef7ac9f }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'